# Generated by Django 4.0.3 on 2022-03-04 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
